### ISSUE TITLE
Init project, blade syntax

### ISSUE THREAD

**Issue by etifontaine** [bestmomo/laravel-artisan-language#1]
Hello, I'm trying to use your package on Laravel but what do you mean by project strings ?
Can you please tell me or show me an example ?

Thank you !

**Comment by bestmomo** [comment]
Hello
The strings are all the texts you put in your code, for example:
`@lang('Next')`
Here the string is "Next", If you want this text in other languages you must create a land file. The package check all strings in code, can create lang JSON files, chekc differences and synchronise a file.
