### ISSUE TITLE
Laravel 6 support

### ISSUE THREAD

**Issue by cyrilbosson** [bestmomo/laravel-artisan-language#4]
Hello,

Can I use your package with Laravel 6 (6.0.3), I tried and I got the following message:

> Problem 1
>     - Installation request for bestmomo/laravel5-artisan-language ^0.1.4 -> satisfiable by bestmomo/laravel5-artisan-language[V0.1.4].
>     - Conclusion: remove laravel/framework v6.0.3
>     - Conclusion: don't install laravel/framework v6.0.3
>     - bestmomo/laravel5-artisan-language V0.1.4 requires illuminate/support ~5.4

Thanks a lot

**Comment by bestmomo** [comment]
Hello

Must work with version 0.1.5

**Comment by cyrilbosson** [comment]
Thanks!
